### ISSUE TITLE
Jest + React Testing Library error

### ISSUE THREAD

**Issue by Drogbi** [alvarotrigo/react-fullpage#258]
### Description

Hi!

Trying to test my code with Jest + React Testing Library and getting the error below. Seems it's related to issue #97. 

I've seen you made a fix here https://github.com/alvarotrigo/react-fullpage/compare/v0.1.8...v0.1.11#diff-545931490bc9fb7bfb72fcc1db6fbf41916a8b0b67a1ae9289c7a7df84d32424 but I noticed that after source code building ` process.env.NODE_ENV.toLowerCase()` becoming `var env="production".toLowerCase()`. It means env always asserts to 'production' even in a test environment. You can check this in the latest release https://github.com/alvarotrigo/react-fullpage/releases/tag/0.1.18

`error:
              Error: Uncaught [TypeError: Cannot read property 'length' of undefined]
    at reportException (/Use...
              "Error: Uncaught [TypeError: Cannot read property 'length' of undefined]\n    at reportException (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)\n    at innerInvokeEventListeners (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)\n    at invokeEventListeners (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)\n    at HTMLUnknownElementImpl._dispatch (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)\n    at HTMLUnknownElementImpl.dispatchEvent (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)\n    at HTMLUnknownElement.dispatchEvent (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)\n    at Object.invokeGuardedCallbackDev (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/modules/TraderProgram/node_modules/react-dom/cjs/react-dom.development.js:237:16)\n    at invokeGuardedCallback (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/modules/TraderProgram/node_modules/react-dom/cjs/react-dom.development.js:292:31)\n    at commitRootImpl (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/modules/TraderProgram/node_modules/react-dom/cjs/react-dom.development.js:22541:9)\n    at unstable_runWithPriority (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/modules/TraderProgram/node_modules/scheduler/cjs/scheduler.development.js:653:12)"
              Cannot read property 'length' of undefined...
              {}
              Error: Uncaught [TypeError: Cannot read property 'destroy' of undefined]
    at reportException (/Us...
              "Error: Uncaught [TypeError: Cannot read property 'destroy' of undefined]\n    at reportException (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)\n    at innerInvokeEventListeners (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)\n    at invokeEventListeners (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)\n    at HTMLUnknownElementImpl._dispatch (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)\n    at HTMLUnknownElementImpl.dispatchEvent (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)\n    at HTMLUnknownElement.dispatchEvent (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)\n    at Object.invokeGuardedCallbackDev (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/modules/TraderProgram/node_modules/react-dom/cjs/react-dom.development.js:237:16)\n    at invokeGuardedCallback (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/modules/TraderProgram/node_modules/react-dom/cjs/react-dom.development.js:292:31)\n    at safelyCallComponentWillUnmount (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/modules/TraderProgram/node_modules/react-dom/cjs/react-dom.development.js:19587:5)\n    at commitUnmount (/Users/aliaksandrihnashevich/PhpstormProjects/appshell-frontend/modules/TraderProgram/node_modules/react-dom/cjs/react-dom.development.js:20109:11)"
              Cannot read property 'destroy' of undefined...
              {}
              The above error occurred in the <ReactFullpage> component:
    in ReactFullpage (created by TraderPr...
              "The above error occurred in the <ReactFullpage> component:\n    in ReactFullpage (created by TraderProgramDesktop)\n    in TraderProgramDesktop\n    in div (created by Context.Consumer)\n    in Media\n    in Unknown\n    in Provider\n    in IntlProvider\n    in Unknown\n\nConsider adding an error boundary to your tree to customize error handling behavior.\nVisit https://fb.me/react-error-boundaries to learn more about error boundaries."
              The above error occurred in the <ReactFullpage> component:
    in ReactFullpage (created by TraderPr...
              "The above error occurred in the <ReactFullpage> component:\n    in ReactFullpage (created by TraderProgramDesktop)\n    in TraderProgramDesktop\n    in div (created by Context.Consumer)\n    in Media\n    in Unknown\n    in Provider\n    in IntlProvider\n    in Unknown\n\nConsider adding an error boundary to your tree to customize error handling behavior.\nVisit https://fb.me/react-error-boundaries to learn more about error boundaries."

`

Chrome: Version 91.0.4472.114 (Official Build) (x86_64)
MacOS: BigSur
Node: v14.17.0

**Comment by alvarotrigo** [comment]
Would you like to provide a pull request for it ?

**Comment by Drogbi** [comment]
> Would you like to provide a pull request for it ?

Yeah, let me try

**Comment by Drogbi** [comment]
> Would you like to provide a pull request for it ?

I tried to and haven't managed to fix it 😞 

Can you take it?

**Comment by alvarotrigo** [comment]
To be honest I'm not familiar with Jest so I'm a bit lost here too :)

**Comment by alvarotrigo** [comment]
Any idea what can be happening @cmswalker ?
